import { getImagePath } from "@/lib/utils";
import { StoreType } from "@/types/store";

const getStoreData = (): StoreType[] => [
  {
    id: 1,
    title: "Royal Supermarket",
    description: "Your daily grocery and fresh vegetable store.",
    image: getImagePath("/images/stores/supermarket.jpg"),
    images: [
      getImagePath("/images/stores/supermarket1.jpg"),
      getImagePath("/images/stores/supermarket2.jpg"),
    ],
    address: "Main Road, Greenpark, Kozhikode",
    location: { lat: 11.258753, lon: 75.78041 },
    phone: "9876543210",
    whatsapp: "9876543210",
    email: "royalsupermarket@gmail.com",
    category: "Grocery",
    isVerified: true,
    rating: 4.5,
    openHours: { open: "08:00 AM", close: "10:00 PM" },
  },
  {
    id: 2,
    title: "FastFix Electrician",
    description: "24/7 electrician service for home and office.",
    image: getImagePath("/images/stores/electrician.jpg"),
    images: [getImagePath("/images/stores/electrician1.jpg")],
    address: "Market Junction, Kunnamangalam",
    location: { lat: 11.301212, lon: 75.931719 },
    phone: "9847001234",
    whatsapp: "9847001234",
    email: "fastfixservice@gmail.com",
    category: "Electrician",
    isVerified: true,
    rating: 4.8,
    openHours: { open: "09:00 AM", close: "08:00 PM" },
  },
  {
    id: 3,
    title: "Fresh Chicken Center",
    description: "Daily fresh chicken and meat delivery.",
    image: getImagePath("/images/stores/chicken.jpg"),
    images: [
      getImagePath("/images/stores/chicken1.jpg"),
      getImagePath("/images/stores/chicken2.jpg"),
    ],
    address: "Near Panchayath Office, Balussery",
    location: { lat: 11.358121, lon: 75.730441 },
    phone: "9633221100",
    whatsapp: "9633221100",
    email: "freshchicken@gmail.com",
    category: "Chicken Center",
    isVerified: false,
    rating: 4.2,
    openHours: { open: "07:00 AM", close: "09:00 PM" },
  },
  {
    id: 4,
    title: "Auto Rickshaw Stand",
    description: "Available for local and town rides, quick pickups.",
    image: getImagePath("/images/stores/auto.jpg"),
    images: [],
    address: "Bus Stand Road, Mukkom",
    location: { lat: 11.325001, lon: 75.937521 },
    phone: "9895005678",
    whatsapp: "9895005678",
    email: "",
    category: "Auto",
    isVerified: false,
    rating: 4.0,
    openHours: { open: "06:00 AM", close: "11:00 PM" },
  },
  {
    id: 5,
    title: "TechPoint Mobile Service",
    description: "Mobile repair, accessories & software support.",
    image: getImagePath("/images/stores/mobile-repair.jpg"),
    images: [getImagePath("/images/stores/mobile-repair1.jpg")],
    address: "City Center, Kozhikode",
    location: { lat: 11.255341, lon: 75.778912 },
    phone: "8078123456",
    whatsapp: "8078123456",
    email: "techpoint@gmail.com",
    category: "Mobile Service",
    isVerified: true,
    rating: 4.7,
    openHours: { open: "09:30 AM", close: "09:30 PM" },
  },
  {
    id: 6,
    title: "Cool Breeze AC Mechanic",
    description: "Professional AC service, gas filling & repairs.",
    image: getImagePath("/images/stores/ac.jpg"),
    images: [getImagePath("/images/stores/ac1.jpg")],
    address: "Near HP Petrol Pump, Nadakkavu",
    location: { lat: 11.275112, lon: 75.769002 },
    phone: "9947001122",
    whatsapp: "9947001122",
    email: "coolbreezeac@gmail.com",
    category: "AC Mechanic",
    isVerified: true,
    rating: 4.6,
    openHours: { open: "09:00 AM", close: "07:00 PM" },
  },
  {
    id: 7,
    title: "City Bakery",
    description: "Fresh cakes, snacks and cool drinks.",
    image: getImagePath("/images/stores/bakery.jpg"),
    images: [
      getImagePath("/images/stores/bakery1.jpg"),
      getImagePath("/images/stores/bakery2.jpg"),
    ],
    address: "City Road, West Nadakkavu",
    location: { lat: 11.27091, lon: 75.781002 },
    phone: "9876501230",
    whatsapp: "9876501230",
    email: "citybakery@gmail.com",
    category: "Bakery",
    isVerified: true,
    rating: 4.4,
    openHours: { open: "07:00 AM", close: "10:00 PM" },
  },
  {
    id: 8,
    title: "Fresh Fruits & Vegetable Mart",
    description: "Farm fresh fruits and veggies daily.",
    image: getImagePath("/images/stores/vegetables.jpg"),
    images: [],
    address: "Highway Junction, Ramanattukara",
    location: { lat: 11.192312, lon: 75.859112 },
    phone: "9800123456",
    whatsapp: "9800123456",
    email: "freshmart@gmail.com",
    category: "Vegetables",
    isVerified: false,
    rating: 4.1,
    openHours: { open: "06:30 AM", close: "09:00 PM" },
  },
  {
    id: 9,
    title: "Golden Scissors Salon",
    description: "Men's grooming and hair styling.",
    image: getImagePath("/images/stores/salon.jpg"),
    images: [getImagePath("/images/stores/salon1.jpg")],
    address: "Opp. Bus Stand, Koyilandy",
    location: { lat: 11.433901, lon: 75.695612 },
    phone: "9847123456",
    whatsapp: "9847123456",
    email: "goldenscissors@gmail.com",
    category: "Salon",
    isVerified: true,
    rating: 4.3,
    openHours: { open: "09:00 AM", close: "09:30 PM" },
  },
  {
    id: 10,
    title: "Lotus Beauty Parlour",
    description: "Ladies beauty services and bridal makeup.",
    image: getImagePath("/images/stores/parlour.jpg"),
    images: [getImagePath("/images/stores/parlour1.jpg")],
    address: "Kadathanad Road, Vadakara",
    location: { lat: 11.608762, lon: 75.590912 },
    phone: "9633001200",
    whatsapp: "9633001200",
    email: "lotusparlour@gmail.com",
    category: "Beauty Parlour",
    isVerified: true,
    rating: 4.7,
    openHours: { open: "09:00 AM", close: "08:00 PM" },
  },
  {
    id: 11,
    title: "Star Pharmacy",
    description: "All medicines and health essentials.",
    image: getImagePath("/images/stores/medical.jpg"),
    images: [],
    address: "Medical College Road, Calicut",
    location: { lat: 11.272221, lon: 75.851112 },
    phone: "9800654321",
    whatsapp: "9800654321",
    email: "starpharmacy@gmail.com",
    category: "Medical Shop",
    isVerified: true,
    rating: 4.9,
    openHours: { open: "08:00 AM", close: "11:00 PM" },
  },
  {
    id: 12,
    title: "Classic Tailor",
    description: "Men & women stitching and alterations.",
    image: getImagePath("/images/stores/tailor.jpg"),
    images: [getImagePath("/images/stores/tailor1.jpg")],
    address: "Market Road, Mukkam",
    location: { lat: 11.329101, lon: 75.936002 },
    phone: "9847555511",
    whatsapp: "9847555511",
    email: "classictailor@gmail.com",
    category: "Tailor",
    isVerified: false,
    rating: 4.0,
    openHours: { open: "09:00 AM", close: "08:30 PM" },
  },
  {
    id: 13,
    title: "Speed Bike Service",
    description: "Two-wheeler repair and oil change.",
    image: getImagePath("/images/stores/bike-service.jpg"),
    images: [],
    address: "Main Road, Feroke",
    location: { lat: 11.179901, lon: 75.841112 },
    phone: "9947123981",
    whatsapp: "9947123981",
    email: "speedbike@gmail.com",
    category: "Bike Service",
    isVerified: true,
    rating: 4.6,
    openHours: { open: "09:00 AM", close: "07:30 PM" },
  },
  {
    id: 14,
    title: "City Stationery Store",
    description: "Books, notebooks, pens, and school items.",
    image: getImagePath("/images/stores/stationery.jpg"),
    images: [],
    address: "Townhall Road, Kozhikode",
    location: { lat: 11.258991, lon: 75.778211 },
    phone: "9895044444",
    whatsapp: "9895044444",
    email: "stationerycity@gmail.com",
    category: "Stationery",
    isVerified: true,
    rating: 4.2,
    openHours: { open: "08:30 AM", close: "09:00 PM" },
  },
  {
    id: 15,
    title: "Tasty Bites Restaurant",
    description: "South Indian & Arabian dishes.",
    image: getImagePath("/images/stores/restaurant.jpg"),
    images: [getImagePath("/images/stores/restaurant1.jpg")],
    address: "Opp. Private Bus Stand, Kappad",
    location: { lat: 11.354812, lon: 75.724112 },
    phone: "9800122211",
    whatsapp: "9800122211",
    email: "tastybites@gmail.com",
    category: "Restaurant",
    isVerified: true,
    rating: 4.6,
    openHours: { open: "11:00 AM", close: "11:00 PM" },
  },
  {
    id: 16,
    title: "Metro Plumber Service",
    description: "Plumbing installation & leakage repair.",
    image: getImagePath("/images/stores/plumber.jpg"),
    images: [getImagePath("/images/stores/plumber1.jpg")],
    address: "Near Mosque Road, Kunnamangalam",
    location: { lat: 11.301021, lon: 75.931221 },
    phone: "9744009988",
    whatsapp: "9744009988",
    email: "metroplumber@gmail.com",
    category: "Plumber",
    isVerified: false,
    rating: 4.1,
    openHours: { open: "08:30 AM", close: "07:00 PM" },
  }
];

export default getStoreData;
